"""
autonomous_executor.py — Autonomous Execution Engine for HELIOS.

Closes the AI decision loop by applying the optimizer's recommended strategy
to the current network state (inside the simulator), generating an updated
snapshot, persisting an execution record, and broadcasting results.

This is a *simulated* execution layer, not a real network controller.
"""

import copy
import time
import uuid
import logging
import datetime
from typing import Dict, Any, Optional

from app.services.strategy_effects import get_strategy_effect

logger = logging.getLogger(__name__)

EXECUTOR_VERSION = "1.0.0"

# ──────────────────────────────────────────────────────────────────────────────
# Strategy name aliases — maps simulator/planner names to executor effect keys
# so that strategies generated by the AI pipeline are always recognised.
# ──────────────────────────────────────────────────────────────────────────────

_STRATEGY_ALIASES: Dict[str, str] = {
    "Dynamic Path Optimisation": "Traffic Redistribution",
    "Traffic Rerouting":        "Traffic Redistribution",
    "QoS Traffic Shaping":      "Traffic Redistribution",
    "Temporary Network Slice":  "Increase Bandwidth",
    "Emergency Network Slice":  "Increase Bandwidth",
    "Slice Reconfiguration":    "Increase Bandwidth",
    "Edge Cache Warming":       "Edge Workload Migration",
    "Edge Load Rebalancing":    "Edge Workload Migration",
    "Activate Backup Tower":    "Emergency Recovery",
    "Disaster Recovery Protocol":"Emergency Recovery",
    "Predictive Component Replacement": "Emergency Recovery",
    "Inter-Tower Load Balancing":"Load Balancing",
    "Power Scaling":            "Power Optimization",
    "Sleep Mode Activation":    "Power Optimization",
}


def _resolve_strategy_name(name: str) -> str:
    """Resolve a strategy name to an executor-known effect key."""
    return _STRATEGY_ALIASES.get(name, name)

# ──────────────────────────────────────────────────────────────────────────────
# Internal helpers
# ──────────────────────────────────────────────────────────────────────────────

def _clamp(value: float, lo: float = 0.0, hi: float = 100.0) -> float:
    """Clamp a value to [lo, hi]."""
    return max(lo, min(hi, value))


def _apply_factor(base: float, factor: float) -> float:
    """Apply a fractional factor (e.g. -0.15 → 15 % decrease)."""
    return base * (1.0 + factor)


def _calculate_health(
    latency: float,
    bandwidth: float,
    packet_loss: float,
    power: float,
    utilization: float,
) -> float:
    """
    Replicates the network health formula used by the Digital Twin metrics
    module so the executor produces consistent health scores.
    """
    lat_score = max(0.0, 100.0 - latency)
    bw_score = min(100.0, bandwidth)
    pl_score = max(0.0, 100.0 - packet_loss * 20.0)
    pwr_score = max(0.0, 100.0 - power)
    util_score = max(0.0, 100.0 - utilization)
    health = (
        0.30 * lat_score
        + 0.25 * bw_score
        + 0.20 * pl_score
        + 0.15 * pwr_score
        + 0.10 * util_score
    )
    return round(_clamp(health), 2)


# ──────────────────────────────────────────────────────────────────────────────
# Autonomous Executor
# ──────────────────────────────────────────────────────────────────────────────

class AutonomousExecutor:
    """
    Receives the best strategy from the optimizer, validates it, applies it
    to the current network state, and produces an updated snapshot along
    with a structured execution report.
    """

    # ── 1. Validation ─────────────────────────────────────────────────────

    def validate_strategy(
        self,
        best_strategy: Dict[str, Any],
    ) -> bool:
        """
        Basic sanity check before execution.

        Returns True if the strategy is safe to apply.
        """
        if not best_strategy:
            logger.warning("Executor: no strategy provided.")
            return False

        name = best_strategy.get("strategy")
        if not name:
            logger.warning("Executor: strategy has no name field.")
            return False

        score = best_strategy.get("score", 0)
        if score <= 0:
            logger.warning("Executor: strategy score is non-positive (%.2f).", score)
            return False

        return True

    # ── 2. Apply Strategy ─────────────────────────────────────────────────

    def apply_strategy(
        self,
        current_state: Dict[str, Any],
        strategy_name: str,
    ) -> Dict[str, Any]:
        """
        Apply the strategy's effect profile to the current network state
        and return a NEW state dict.  The original is never mutated.
        """
        state = copy.deepcopy(current_state)
        resolved_name = _resolve_strategy_name(strategy_name)
        effect = get_strategy_effect(resolved_name)

        # Compute health-before if missing (raw telemetry doesn't include it)
        if "network_health" not in state:
            state["network_health"] = _calculate_health(
                float(state.get("latency_ms", 30.0)),
                float(state.get("available_bandwidth_mbps", 50.0)),
                float(state.get("packet_loss_pct", 1.0)),
                float(state.get("power_usage_pct", 50.0)),
                float(state.get("tower_utilization_pct",
                      min(100, (float(state.get("users", 500)) / 1000) * 100))),
            )

        # Users
        users = float(state.get("users", 500))
        users = max(1, round(_apply_factor(users, effect["users_factor"])))
        state["users"] = users

        # Bandwidth
        bw = float(state.get("available_bandwidth_mbps", 50.0))
        bw = round(max(0.0, bw + effect["bandwidth_delta"]), 2)
        state["available_bandwidth_mbps"] = bw

        # Latency
        lat = float(state.get("latency_ms", 30.0))
        lat = round(max(0.0, _apply_factor(lat, effect["latency_factor"])), 2)
        state["latency_ms"] = lat

        # Packet loss
        pl = float(state.get("packet_loss_pct", 1.0))
        pl = round(_clamp(_apply_factor(pl, effect["packet_loss_factor"]), 0.0, 10.0), 2)
        state["packet_loss_pct"] = pl

        # Tower utilization (estimated from users if missing)
        util = float(state.get("tower_utilization_pct", min(100, (users / 1000) * 100)))
        util = round(_clamp(_apply_factor(util, effect["tower_utilization_factor"])), 2)
        state["tower_utilization_pct"] = util

        # Power
        pwr = float(state.get("power_usage_pct", 50.0))
        pwr = round(_clamp(pwr + effect["power_delta"]), 2)
        state["power_usage_pct"] = pwr

        # Temperature
        temp = float(state.get("temperature_c", 40.0))
        temp = round(max(0.0, temp + effect["temperature_delta"]), 2)
        state["temperature_c"] = temp

        # Edge CPU
        cpu = float(state.get("cpu_usage_pct", 50.0))
        cpu = round(_clamp(_apply_factor(cpu, effect["edge_cpu_factor"])), 2)
        state["cpu_usage_pct"] = cpu

        # Edge memory
        mem = float(state.get("memory_usage_pct", 45.0))
        mem = round(_clamp(_apply_factor(mem, effect["edge_memory_factor"])), 2)
        state["memory_usage_pct"] = mem

        # Recalculate network health
        state["network_health"] = _calculate_health(
            lat, bw, pl, pwr, util,
        )

        # ── Apply Slice Reallocation Logic ────────────────────────────────────
        if resolved_name == "Dynamic Slice Reallocation":
            slices = state.get("slices", [])
            
            # Record violations before
            violations_before = [s["name"] for s in slices if s["status"] in ["VIOLATION", "DEGRADED"]]
            
            for s in slices:
                if s["status"] in ["VIOLATION", "DEGRADED"]:
                    # Increase allocation to meet demand + 20%
                    demand = s["current_demand_mbps"]
                    target_alloc = min(demand * 1.2, s["maximum_bandwidth_mbps"])
                    s["allocated_bandwidth_mbps"] = round(target_alloc, 2)
                    
                    # Assume execution fixes it immediately
                    s["current_latency_ms"] = s["latency_target_ms"] * 0.8
                    s["current_packet_loss_pct"] = s["packet_loss_target_pct"] * 0.5
                    s["status"] = "HEALTHY"
                    
                elif s["priority"] in ["NORMAL", "LOW"] and s["allocated_bandwidth_mbps"] > s["current_demand_mbps"]:
                    # Reclaim surplus
                    surplus = s["allocated_bandwidth_mbps"] - s["current_demand_mbps"]
                    s["allocated_bandwidth_mbps"] = round(s["allocated_bandwidth_mbps"] - (surplus * 0.5), 2)

        return state

    # ── 3. Build Execution Report ─────────────────────────────────────────

    def _build_report(
        self,
        strategy_name: str,
        state_before: Dict[str, Any],
        state_after: Dict[str, Any],
        status: str,
        elapsed_ms: float,
    ) -> Dict[str, Any]:
        """Constructs the structured execution report."""
        health_before = float(state_before.get("network_health", 0.0))
        health_after = float(state_after.get("network_health", 0.0))
        improvement = round(health_after - health_before, 2)

        # Build a delta summary of every KPI that changed
        tracked_metrics = [
            "users", "available_bandwidth_mbps", "latency_ms",
            "packet_loss_pct", "tower_utilization_pct", "power_usage_pct",
            "temperature_c", "cpu_usage_pct", "memory_usage_pct",
            "network_health",
        ]
        changed: Dict[str, Dict[str, float]] = {}
        for key in tracked_metrics:
            before_val = state_before.get(key)
            after_val = state_after.get(key)
            if before_val is not None and after_val is not None:
                b = round(float(before_val), 2)
                a = round(float(after_val), 2)
                if b != a:
                    changed[key] = {"before": b, "after": a, "delta": round(a - b, 2)}

        # Capture slice changes if present
        slice_changes = []
        sla_violations_before = []
        sla_violations_after = []
        
        slices_before = {s["name"]: s for s in state_before.get("slices", [])}
        slices_after = {s["name"]: s for s in state_after.get("slices", [])}
        
        for name, sb in slices_before.items():
            if sb["status"] in ["VIOLATION", "DEGRADED"]:
                sla_violations_before.append(name)
            
            sa = slices_after.get(name)
            if sa:
                if sa["status"] in ["VIOLATION", "DEGRADED"]:
                    sla_violations_after.append(name)
                    
                if sb["allocated_bandwidth_mbps"] != sa["allocated_bandwidth_mbps"]:
                    slice_changes.append({
                        "name": name,
                        "before_mbps": sb["allocated_bandwidth_mbps"],
                        "after_mbps": sa["allocated_bandwidth_mbps"],
                        "status_before": sb["status"],
                        "status_after": sa["status"]
                    })

        report_dict = {
            "execution_id": str(uuid.uuid4()),
            "strategy": strategy_name,
            "status": status,
            "execution_time_ms": elapsed_ms,
            "changed_metrics": changed,
            "network_health_before": health_before,
            "network_health_after": health_after,
            "improvement_score": improvement,
            "generated_at": datetime.datetime.utcnow().isoformat() + "Z",
        }
        
        if slice_changes or sla_violations_before:
            report_dict["slice_changes"] = slice_changes
            report_dict["sla_violations_before"] = sla_violations_before
            report_dict["sla_violations_after"] = sla_violations_after
            
        return report_dict

    # ── 4. Public API ─────────────────────────────────────────────────────

    def execute(
        self,
        current_state: Dict[str, Any],
        optimization_result: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Full autonomous execution cycle.

        Args:
            current_state:       The telemetry dict from the current snapshot.
            optimization_result: The full output from the Multi-objective
                                 Optimizer (contains 'recommended_strategy').

        Returns:
            {
                "execution_report": { ... },
                "updated_state": { ... },        # new network state
            }
        """
        start = time.perf_counter()
        logger.info("Autonomous Executor started")

        best = optimization_result.get("recommended_strategy")

        # Validate
        if not self.validate_strategy(best):
            elapsed = round((time.perf_counter() - start) * 1000, 2)
            report = self._build_report(
                strategy_name="None",
                state_before=current_state,
                state_after=current_state,
                status="skipped",
                elapsed_ms=elapsed,
            )
            logger.warning("Executor: strategy validation failed — skipping execution.")
            return {"execution_report": report, "updated_state": current_state}

        strategy_name = best["strategy"]
        logger.info("Executing strategy: '%s'", strategy_name)

        # Apply
        state_before = copy.deepcopy(current_state)
        # Ensure health-before is computed on the pre-execution state
        if "network_health" not in state_before:
            state_before["network_health"] = _calculate_health(
                float(state_before.get("latency_ms", 30.0)),
                float(state_before.get("available_bandwidth_mbps", 50.0)),
                float(state_before.get("packet_loss_pct", 1.0)),
                float(state_before.get("power_usage_pct", 50.0)),
                float(state_before.get("tower_utilization_pct",
                      min(100, (float(state_before.get("users", 500)) / 1000) * 100))),
            )
        updated_state = self.apply_strategy(current_state, strategy_name)

        elapsed = round((time.perf_counter() - start) * 1000, 2)

        report = self._build_report(
            strategy_name=strategy_name,
            state_before=state_before,
            state_after=updated_state,
            status="executed",
            elapsed_ms=elapsed,
        )

        logger.info(
            "Executor finished — '%s' applied in %.2f ms  |  health %.1f → %.1f  (Δ %+.1f)",
            strategy_name,
            elapsed,
            report["network_health_before"],
            report["network_health_after"],
            report["improvement_score"],
        )

        return {
            "execution_report": report,
            "updated_state": updated_state,
        }


# ──────────────────────────────────────────────────────────────────────────────
# Public convenience function
# ──────────────────────────────────────────────────────────────────────────────

def helios_execute(
    current_state: Dict[str, Any],
    optimization_result: Dict[str, Any],
) -> Dict[str, Any]:
    """Public wrapper — instantiates the executor and runs it."""
    executor = AutonomousExecutor()
    return executor.execute(current_state, optimization_result)
