"""Sync AI models

Revision ID: 30663f356907
Revises: fee84a20d139
Create Date: 2026-08-08 04:45:41.243929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30663f356907'
down_revision: Union[str, Sequence[str], None] = 'fee84a20d139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edge_servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('edge_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_servers_edge_id'), 'edge_servers', ['edge_id'], unique=True)
    op.create_table('execution_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('execution_status', sa.String(), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('snapshot_before', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot_after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('improvement_score', sa.Float(), nullable=False),
    sa.Column('changed_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_history_strategy'), 'execution_history', ['strategy'], unique=False)
    op.create_index(op.f('ix_execution_history_timestamp'), 'execution_history', ['timestamp'], unique=False)
    op.create_table('explainability_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('prediction_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strategy_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('simulation_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('execution_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('helios_insight', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explainability_history_snapshot_id'), 'explainability_history', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_explainability_history_timestamp'), 'explainability_history', ['timestamp'], unique=False)
    op.create_table('network_health',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('packet_loss_pct', sa.Float(), nullable=False),
    sa.Column('availability_pct', sa.Float(), nullable=False),
    sa.Column('energy_usage_pct', sa.Float(), nullable=False),
    sa.Column('resource_utilization_pct', sa.Float(), nullable=False),
    sa.Column('overall_health_index', sa.Float(), nullable=False),
    sa.Column('health_category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_health_timestamp'), 'network_health', ['timestamp'], unique=False)
    op.create_table('network_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('telemetry', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prediction', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strategies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('simulation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_snapshots_timestamp'), 'network_snapshots', ['timestamp'], unique=False)
    op.create_table('scenario_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('scenario_name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('affected_towers', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('affected_edges', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('snapshot_before', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot_after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_history_scenario_id'), 'scenario_history', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_scenario_history_scenario_name'), 'scenario_history', ['scenario_name'], unique=False)
    op.create_index(op.f('ix_scenario_history_timestamp'), 'scenario_history', ['timestamp'], unique=False)
    op.create_table('towers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tower_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_towers_tower_id'), 'towers', ['tower_id'], unique=True)
    op.create_table('edge_telemetry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('edge_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('cpu_pct', sa.Float(), nullable=False),
    sa.Column('gpu_pct', sa.Float(), nullable=False),
    sa.Column('memory_pct', sa.Float(), nullable=False),
    sa.Column('requests_per_min', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('edge_health', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['edge_id'], ['edge_servers.edge_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_telemetry_edge_id'), 'edge_telemetry', ['edge_id'], unique=False)
    op.create_index(op.f('ix_edge_telemetry_timestamp'), 'edge_telemetry', ['timestamp'], unique=False)
    op.create_table('failures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tower_id', sa.String(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('power_usage_pct', sa.Float(), nullable=False),
    sa.Column('traffic_load', sa.Float(), nullable=False),
    sa.Column('weather', sa.String(), nullable=False),
    sa.Column('cpu_usage_pct', sa.Float(), nullable=False),
    sa.Column('failed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.tower_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failures_tower_id'), 'failures', ['tower_id'], unique=False)
    op.create_table('tower_utilization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tower_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('users', sa.Integer(), nullable=False),
    sa.Column('available_bandwidth_mbps', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('packet_loss_pct', sa.Float(), nullable=False),
    sa.Column('power_usage_pct', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('utilization_score', sa.Float(), nullable=False),
    sa.Column('congested', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.tower_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tower_utilization_timestamp'), 'tower_utilization', ['timestamp'], unique=False)
    op.create_index(op.f('ix_tower_utilization_tower_id'), 'tower_utilization', ['tower_id'], unique=False)
    op.create_table('traffic',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tower_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('video_users', sa.Integer(), nullable=False),
    sa.Column('voice_users', sa.Integer(), nullable=False),
    sa.Column('iot_devices', sa.Integer(), nullable=False),
    sa.Column('gaming_users', sa.Integer(), nullable=False),
    sa.Column('emergency_users', sa.Integer(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.tower_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_timestamp'), 'traffic', ['timestamp'], unique=False)
    op.create_index(op.f('ix_traffic_tower_id'), 'traffic', ['tower_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_tower_id'), table_name='traffic')
    op.drop_index(op.f('ix_traffic_timestamp'), table_name='traffic')
    op.drop_table('traffic')
    op.drop_index(op.f('ix_tower_utilization_tower_id'), table_name='tower_utilization')
    op.drop_index(op.f('ix_tower_utilization_timestamp'), table_name='tower_utilization')
    op.drop_table('tower_utilization')
    op.drop_index(op.f('ix_failures_tower_id'), table_name='failures')
    op.drop_table('failures')
    op.drop_index(op.f('ix_edge_telemetry_timestamp'), table_name='edge_telemetry')
    op.drop_index(op.f('ix_edge_telemetry_edge_id'), table_name='edge_telemetry')
    op.drop_table('edge_telemetry')
    op.drop_index(op.f('ix_towers_tower_id'), table_name='towers')
    op.drop_table('towers')
    op.drop_index(op.f('ix_scenario_history_timestamp'), table_name='scenario_history')
    op.drop_index(op.f('ix_scenario_history_scenario_name'), table_name='scenario_history')
    op.drop_index(op.f('ix_scenario_history_scenario_id'), table_name='scenario_history')
    op.drop_table('scenario_history')
    op.drop_index(op.f('ix_network_snapshots_timestamp'), table_name='network_snapshots')
    op.drop_table('network_snapshots')
    op.drop_index(op.f('ix_network_health_timestamp'), table_name='network_health')
    op.drop_table('network_health')
    op.drop_index(op.f('ix_explainability_history_timestamp'), table_name='explainability_history')
    op.drop_index(op.f('ix_explainability_history_snapshot_id'), table_name='explainability_history')
    op.drop_table('explainability_history')
    op.drop_index(op.f('ix_execution_history_timestamp'), table_name='execution_history')
    op.drop_index(op.f('ix_execution_history_strategy'), table_name='execution_history')
    op.drop_table('execution_history')
    op.drop_index(op.f('ix_edge_servers_edge_id'), table_name='edge_servers')
    op.drop_table('edge_servers')
    # ### end Alembic commands ###
