"""Add NetworkSlice model

Revision ID: a14faea3860f
Revises: 30663f356907
Create Date: 2026-08-08 08:57:27.490550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a14faea3860f'
down_revision: Union[str, Sequence[str], None] = '30663f356907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_slices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slice_id', sa.String(), nullable=False),
    sa.Column('tower_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slice_type', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('allocated_bandwidth_mbps', sa.Float(), nullable=False),
    sa.Column('minimum_bandwidth_mbps', sa.Float(), nullable=False),
    sa.Column('maximum_bandwidth_mbps', sa.Float(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('current_demand_mbps', sa.Float(), nullable=False),
    sa.Column('current_latency_ms', sa.Float(), nullable=False),
    sa.Column('current_packet_loss_pct', sa.Float(), nullable=False),
    sa.Column('latency_target_ms', sa.Float(), nullable=False),
    sa.Column('packet_loss_target_pct', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.tower_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_slices_slice_id'), 'network_slices', ['slice_id'], unique=True)
    op.create_index(op.f('ix_network_slices_tower_id'), 'network_slices', ['tower_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_network_slices_tower_id'), table_name='network_slices')
    op.drop_index(op.f('ix_network_slices_slice_id'), table_name='network_slices')
    op.drop_table('network_slices')
    # ### end Alembic commands ###
